namespace: ansible
name: skydive
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:coll-test/ansible.skydive.git
documentation: https://github.com/coll-test/ansible.skydive/tree/master/docs
homepage: https://github.com/coll-test/ansible.skydive
issues: https://github.com/coll-test/ansible.skydive/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
